#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of the tool.
#
TOOLNAME=fex

#
# List libraries that we'll need
# We use LIBS because sample is a dynamic library.
#
USEDLIBS = 
LINK_COMPONENTS = support

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

