GAIUS_LEVEL := ../..

TOOLNAME = fex
NO_INSTALL = 1

# No plugins, optimize startup time.
TOOL_NO_EXPORTS = 1

LINK_COMPONENTS := support
USEDLIBS := clangFrontend.a clangParse.a clangLex.a clangBasic.a

include $(GAIUS_LEVEL)/Makefile
