#
# Indicates our relative path to the top of the project's root directory.
#
GAIUS_LEVEL := ..
DIRS := fex

#
# Include the Master Makefile that knows how to build all.
#
include $(GAIUS_LEVEL)/Makefile

